### ISSUE TITLE
remoteApiURL questions

### ISSUE THREAD

**Issue by arjenblokzijl** [IanW6374/homebridge-dynamicAPI#4]
Hi, 

I'm trying to configure this plug-in, but it is unclear to me as to which is my `remoteApiURL`. I'm running Homebridge in a docker container (on my nas) on port x.x.x.x:8581. Based on the logs dynamicAPI wants to read some json, but what value should I address to `remoteApiURL`? The direct connect API seems to be working fine.

```
[11/17/2021, 8:57:42 PM] [dynamicAPI] [Platform Error]:  Remote API GET Failure: FetchError: request to http://192.168.178.36:8003/api/ failed, reason: connect ECONNREFUSED 192.168.178.36:8003
```

Thanks in advance!

**Comment by IanW6374** [comment]
The “remoteApiURL” is the URL of the host which is controlling the physical devices via API - see the associated project for details

**Comment by arjenblokzijl** [comment]
Thanks will take a look!
